### ISSUE TITLE
better service communication

### ISSUE THREAD

**Issue by eankeen** [eankeen/tails#4]
so right now we are using raw http reqs for calling in between microservices

obviously this is pretty jank so were going to have to implement some message broker to facilitate better communication

was looking into solutions including rabbitmq, apache kafka, and nats. after almost choosing each one separately i finally decided on nats. mainly because it fits in the cncf ecosystem and it is as simple as we need it - even if its not as popular as kafka or rabbitmq. considered kafka over rabbitmq, but its probably too heavy weight, not to mention zookeeper and jvm overhead. maintenance of it within our app will probably be difficult (and have a suboptimal configuration), since i do not have a strong background in distributed system development

going to close this issue once our services integrate with nats pretty :ok_hand:

**Comment by hyperupcall** [comment]
alright architecture changed again. now we're doing service to service communicating with grpc. closing as issue no longer relevant
